package edu.odu.cs.cs600.calculator.math.grammar;

/**
 * Base Token class.  Generated by the Lexer and consumed by the Parser.
 * 
 * Taken from: https://github.com/munificent/bantam/blob/master/src/com/stuffwithstuff/bantam/Token.java
 * Write-up: http://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/
 */
public final class Token {
	private final TokenType tokenType;
	private final String lexeme;
	
	public Token(TokenType tokenType, String lexeme) {
		this.tokenType = tokenType;
		this.lexeme = lexeme;
	}
	
	
	
	public TokenType getTokenType() {
		return tokenType;
	}
	
	
	
	public String getLexeme() {
		return lexeme;
	}
}